import sqlalchemy as sa
from alembic import op

revision = "38a99beba54f"
down_revision = "15bca5e3069c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker_runs", sa.Column("session_id", sa.String(length=255), nullable=True))
    op.add_column(
        "worker_runs", sa.Column("requested_permission", sa.String(length=255), nullable=True)
    )
    op.add_column("worker_runs", sa.Column("budget_usage", sa.JSON(), nullable=True))
    op.add_column("worker_runs", sa.Column("verifier_outcome", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_worker_runs_session_id"), "worker_runs", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_worker_runs_session_id"), table_name="worker_runs")
    op.drop_column("worker_runs", "verifier_outcome")
    op.drop_column("worker_runs", "budget_usage")
    op.drop_column("worker_runs", "requested_permission")
    op.drop_column("worker_runs", "session_id")
    # ### end Alembic commands ###
