"""Add skeptical memory and session state"""

import sqlalchemy as sa
from alembic import op

revision = "15bca5e3069c"
down_revision = "20260404_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_states",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("active_goal", sa.Text(), nullable=True),
        sa.Column("decisions_made", sa.JSON(), nullable=False),
        sa.Column("identified_risks", sa.JSON(), nullable=False),
        sa.Column("files_touched", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_states_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_states")),
    )
    op.create_index(
        op.f("ix_session_states_session_id"), "session_states", ["session_id"], unique=True
    )
    op.add_column("memory_personal", sa.Column("source", sa.String(length=255), nullable=True))
    op.add_column(
        "memory_personal",
        sa.Column("confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False),
    )
    op.add_column("memory_personal", sa.Column("scope", sa.String(length=255), nullable=True))
    op.add_column(
        "memory_personal", sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "memory_personal",
        sa.Column(
            "requires_verification", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column("memory_project", sa.Column("source", sa.String(length=255), nullable=True))
    op.add_column(
        "memory_project",
        sa.Column("confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False),
    )
    op.add_column("memory_project", sa.Column("scope", sa.String(length=255), nullable=True))
    op.add_column(
        "memory_project", sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "memory_project",
        sa.Column(
            "requires_verification", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column("worker_runs", sa.Column("files_changed", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker_runs", "files_changed")
    op.drop_column("memory_project", "requires_verification")
    op.drop_column("memory_project", "last_verified_at")
    op.drop_column("memory_project", "scope")
    op.drop_column("memory_project", "confidence")
    op.drop_column("memory_project", "source")
    op.drop_column("memory_personal", "requires_verification")
    op.drop_column("memory_personal", "last_verified_at")
    op.drop_column("memory_personal", "scope")
    op.drop_column("memory_personal", "confidence")
    op.drop_column("memory_personal", "source")
    op.drop_index(op.f("ix_session_states_session_id"), table_name="session_states")
    op.drop_table("session_states")
    # ### end Alembic commands ###
