"""Add queue_lane to tasks"""

revision = "7d9ec93c991e"
down_revision = "1ff838f95c30"
branch_labels = None
depends_on = None


import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("queue_lane", sa.String(length=50), nullable=False, server_default="primary"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "queue_lane")
    # ### end Alembic commands ###
