"""Add HumanInteraction model"""

import sqlalchemy as sa
from alembic import op

revision = "d5d89f9b407a"
down_revision = "20260427_0020"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "human_interactions",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column(
            "interaction_type",
            sa.Enum(
                "clarification",
                "permission",
                "review",
                "merge",
                "blocked_help",
                name="human_interaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "resolved",
                "rejected",
                "cancelled",
                name="human_interaction_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("response_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_human_interactions_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_interactions")),
    )
    op.create_index(
        "ix_human_interactions_task_id_status",
        "human_interactions",
        ["task_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_human_interactions_task_id_status", table_name="human_interactions")
    op.drop_table("human_interactions")
    # ### end Alembic commands ###
