"""add execution plan models"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "e0cffe741eb4"
down_revision = "4f9570d10dd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_plans",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_execution_plans_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_plans")),
    )
    op.create_index(op.f("ix_execution_plans_task_id"), "execution_plans", ["task_id"], unique=True)
    op.create_table(
        "execution_plan_nodes",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=255), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("depends_on", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "blocked",
                "completed",
                "failed",
                "skipped",
                name="execution_plan_node_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("acceptance_criteria", sa.Text(), nullable=True),
        sa.Column("assigned_worker_profile", sa.String(length=255), nullable=True),
        sa.Column("budget", sa.JSON(), nullable=True),
        sa.Column("validation_commands", sa.JSON(), nullable=True),
        sa.Column("artifacts", sa.JSON(), nullable=True),
        sa.Column("blocker_interaction_id", sa.String(length=36), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blocker_interaction_id"],
            ["human_interactions.id"],
            name=op.f("fk_execution_plan_nodes_blocker_interaction_id_human_interactions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["execution_plans.id"],
            name=op.f("fk_execution_plan_nodes_plan_id_execution_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_plan_nodes")),
    )
    op.create_index(
        op.f("ix_execution_plan_nodes_plan_id"), "execution_plan_nodes", ["plan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_plan_nodes_plan_id"), table_name="execution_plan_nodes")
    op.drop_table("execution_plan_nodes")
    op.drop_index(op.f("ix_execution_plans_task_id"), table_name="execution_plans")
    op.drop_table("execution_plans")
    # ### end Alembic commands ###
