"""Structured Scout proposal contracts and validation helpers."""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from typing import Any, Final

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from orchestrator.reflection import EffortScore, HitlNeed, LayerImpact, RiskScore, ValueScore
from workers.base import WorkerResult

DEFAULT_MAX_SCOUT_PROPOSALS: Final = 3


class ScoutProposal(BaseModel):
    """A structured proposal generated by a read-only Scout run."""

    model_config = ConfigDict(extra="forbid")

    title: str = Field(min_length=1)
    description: str = Field(min_length=1)
    value: ValueScore
    effort: EffortScore
    risk: RiskScore
    layer_impact: LayerImpact
    validation_path: str = Field(min_length=1)
    hitl_need: HitlNeed
    evidence: list[str] = Field(min_length=1)
    implementation_slice: str = Field(min_length=1)


class ScoutProposalBatch(BaseModel):
    """Top-level structured Scout worker response."""

    model_config = ConfigDict(extra="forbid")

    proposals: list[ScoutProposal] = Field(min_length=1)


class ScoutProposalValidationError(ValueError):
    """Raised when a Scout worker payload does not match the required contract."""


def scout_max_proposals_from_constraints(constraints: Mapping[str, Any]) -> int:
    """Return the normalized per-worker Scout proposal cap."""
    raw_max_proposals = constraints.get("max_proposals")
    try:
        max_proposals = int(raw_max_proposals) if raw_max_proposals is not None else None
    except (TypeError, ValueError):
        max_proposals = None
    if max_proposals is None or max_proposals <= 0:
        return DEFAULT_MAX_SCOUT_PROPOSALS
    return max_proposals


def _mark_all_object_properties_required(schema_node: Any) -> None:
    if isinstance(schema_node, dict):
        properties = schema_node.get("properties")
        if isinstance(properties, dict):
            schema_node["required"] = list(properties.keys())
        for value in schema_node.values():
            _mark_all_object_properties_required(value)
    elif isinstance(schema_node, list):
        for value in schema_node:
            _mark_all_object_properties_required(value)


def scout_response_schema_for_constraints(constraints: Mapping[str, Any]) -> dict[str, Any]:
    """Return the strict JSON schema supplied to Scout workers."""
    max_proposals = scout_max_proposals_from_constraints(constraints)
    schema = ScoutProposalBatch.model_json_schema()
    _mark_all_object_properties_required(schema)
    proposals_schema = schema.get("properties", {}).get("proposals")
    if isinstance(proposals_schema, dict):
        proposals_schema["maxItems"] = max_proposals
    return schema


def validate_scout_proposal_payload(
    payload: dict[str, Any] | None,
    *,
    max_proposals: int,
) -> ScoutProposalBatch:
    """Validate a Scout worker JSON payload and enforce the request item cap."""
    if payload is None:
        raise ScoutProposalValidationError("Scout worker did not return a JSON payload.")
    try:
        batch = ScoutProposalBatch.model_validate(payload)
    except ValidationError as exc:
        raise ScoutProposalValidationError(
            "Scout worker JSON payload did not match the ScoutProposalBatch schema."
        ) from exc
    if len(batch.proposals) > max_proposals:
        raise ScoutProposalValidationError(
            f"Scout worker returned {len(batch.proposals)} proposal(s), "
            f"exceeding the max_proposals cap of {max_proposals}."
        )
    return batch


def normalize_scout_worker_result(
    result: WorkerResult,
    *,
    constraints: Mapping[str, Any],
) -> WorkerResult:
    """Convert structurally invalid successful Scout output into a worker failure."""
    if result.status != "success":
        return result
    max_proposals = scout_max_proposals_from_constraints(constraints)
    try:
        batch = validate_scout_proposal_payload(result.json_payload, max_proposals=max_proposals)
    except ScoutProposalValidationError as exc:
        return result.model_copy(
            update={
                "status": "failure",
                "failure_kind": "incomplete_delivery",
                "summary": str(exc),
            }
        )
    return result.model_copy(update={"json_payload": batch.model_dump(mode="json")})


def compute_scout_proposal_fingerprint(
    proposal: ScoutProposal,
    *,
    task_id: str,
    phase: str | None,
) -> str:
    """Return the stable fingerprint used to dedupe Scout proposal items."""
    normalized_title = proposal.title.strip()
    normalized_description = proposal.description.strip()
    normalized_phase = (phase or "single").strip()
    fingerprint_input = (
        f"{task_id}:{normalized_phase}:{normalized_title}:{normalized_description}"
    ).encode()
    return hashlib.sha256(fingerprint_input).hexdigest()
