import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { CheckCircle, XCircle, Lightbulb } from 'lucide-react';
import { api, ApiError } from '../services/api';
import { ProposalSnapshot, ProposalStatus } from '../types/proposal';
import { DashboardLayout } from './layout/DashboardLayout';

export function IdeaInboxPage() {
  const queryClient = useQueryClient();
  const [actionError, setActionError] = useState<string | null>(null);

  const { data: proposals = [], isLoading, error, refetch } = useQuery({
    queryKey: ['proposals', ProposalStatus.PENDING_REVIEW],
    queryFn: () => api.listProposals(ProposalStatus.PENDING_REVIEW),
    refetchInterval: 30000,
  });

  const acceptMutation = useMutation({
    mutationFn: (proposalId: string) => api.acceptProposal(proposalId),
    onMutate: () => {
      setActionError(null);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['proposals'] });
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
      setActionError(null);
      // Navigate to the newly created task's detail view by going to Dashboard and selecting it,
      // or just refresh the tasks.
      // For now, we stay on the Idea Inbox and it refreshes.
    },
    onError: (err) => {
      const msg = err instanceof ApiError ? err.message : 'Failed to accept proposal';
      setActionError(msg);
    },
  });

  const rejectMutation = useMutation({
    mutationFn: (proposalId: string) => api.rejectProposal(proposalId),
    onMutate: () => {
      setActionError(null);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['proposals'] });
      setActionError(null);
    },
    onError: (err) => {
      const msg = err instanceof ApiError ? err.message : 'Failed to reject proposal';
      setActionError(msg);
    },
  });

  const handleAccept = (proposal: ProposalSnapshot) => {
    acceptMutation.mutate(proposal.proposal_id);
  };

  const handleReject = (proposal: ProposalSnapshot) => {
    if (window.confirm('Are you sure you want to reject this idea?')) {
      rejectMutation.mutate(proposal.proposal_id);
    }
  };

  return (
    <DashboardLayout>
      <div className="metrics-page">
        <header className="metrics-header">
          <div className="header-title">
            <Lightbulb className="header-icon" />
            <h2>Idea Inbox</h2>
          </div>
          <p className="header-description">
            Review proposals and ideas generated by Scout tasks. Accept them to promote to real tasks.
          </p>
        </header>

        {error ? (
          <div className="error-banner">
            Failed to load proposals: {error instanceof Error ? error.message : String(error)}
            <button onClick={() => refetch()} className="retry-button">Retry</button>
          </div>
        ) : null}

        {actionError ? (
          <div className="error-banner">
            Action failed: {actionError}
            <button onClick={() => setActionError(null)} className="retry-button">Dismiss</button>
          </div>
        ) : null}

        <div className="proposals-list">
          {isLoading ? (
            <div className="loading-state">Loading proposals...</div>
          ) : proposals.length === 0 ? (
            <div className="empty-state">
              <Lightbulb size={48} className="empty-icon" />
              <h3>No pending proposals</h3>
              <p>When Scout tasks generate ideas, they will appear here for your review.</p>
            </div>
          ) : (
            <div className="card-grid">
              {proposals.map((proposal) => (
                <div key={proposal.proposal_id} className="memory-card">
                  <div className="memory-header">
                    <h3 className="memory-key">{proposal.title}</h3>
                    <div className="memory-source">{new Date(proposal.created_at).toLocaleString()}</div>
                  </div>
                  <div className="memory-content">
                    <p>{proposal.summary}</p>
                    {proposal.content && (
                      <div className="proposal-details">
                        <details>
                          <summary>View Details</summary>
                          <pre className="json-viewer">{proposal.content}</pre>
                        </details>
                      </div>
                    )}
                  </div>
                  <div className="memory-footer">
                    <button
                      className="button button-success"
                      onClick={() => handleAccept(proposal)}
                      disabled={acceptMutation.isPending || rejectMutation.isPending}
                    >
                      <CheckCircle size={16} /> Accept Idea
                    </button>
                    <button
                      className="button button-danger"
                      onClick={() => handleReject(proposal)}
                      disabled={acceptMutation.isPending || rejectMutation.isPending}
                    >
                      <XCircle size={16} /> Reject
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
